config/routes.rb
CloudSlicer::Application.routes.draw do
  ActiveAdmin.routes(self)

  require 'resque/server'
  mount Resque::Server.new, :at => "/admin/resque"

  root :to => "home#index"

  devise_for :users, :path => '/', :path_names => {:registration => "register"}

  get 'autocomplete/user' => 'users#autocomplete_user_username'

  namespace :api do
    namespace :v1 do # TODO: :constraints => {:subdomain => "admin"}
      resource :print_queues, :path => "/:print_queue_id", :only => [:show, :update] do
        match "load_next_job"
        match "start_printing"
        match "finish_printing"
        get "print_jobs" => "print_jobs#index"
        resource :print_jobs, :path => "print_jobs/:id", :only => [:show, :update]
      end
    end
  end

  resources :users, :path => "/", :except => :index do

    resources :print_queues, :path => "/", :except => :index do
      match "add_role", :on => :member
      match "delete_role", :on => :member

      resources :print_jobs, :only => [:create, :update, :destroy, :index, :show_modal] do
        member do
          get "show_modal"
          get "download"
        end
      end

      resources :g_code_profiles do
        member do
          get "download"
        end
      end

    end

  end

end

app/models/user.rb
require "devise_invitable/model"

class User < ActiveRecord::Base

  # Roles and Permissions
  # ---------------------------------------------------------------------

  rolify

  def configure_with_role(role_sym, resource, opts = {:validate_role => true})
    if resource.present? and opts[:validate_role]
      raise "Invalid Role" unless resource.user_roles.include?(role_sym)
    end

    # Add the new role
    role = self.add_role role_sym, resource

    # Remove any other roles this user has for the resource
    if resource.present?
      resource.user_roles.reject{|r| r == role_sym}.each do |other_role_sym|
        self.remove_role other_role_sym, resource
      end
    end

    return role
  end


  # Devise Authentication
  # ---------------------------------------------------------------------

  attr_accessible :email, :password, :password_confirmation, :username

  devise :invitable, :database_authenticatable, :registerable, :lockable, :recoverable,
           :rememberable, :trackable, :validatable,
           #:confirmable, :allow_unconfirmed_access_for => 1.day,
           :authentication_keys => [:login]


  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login
  attr_accessible :login
  validates_uniqueness_of :username, :allow_blank => true
  validates_uniqueness_of :email

  has_many :print_queues, :as => "owner", :dependent => :destroy

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end


  # Instance Methods
  # ---------------------------------------------------------------------

  # show the gravatar image for a profile - based on their email
  def gravatar_url(size = 100)
    email_md5 = Digest::MD5.hexdigest(email).to_s
    "http://www.gravatar.com/avatar/#{email_md5}?s=#{size}&d=mm"
  end

  def to_s
    username
  end

  def to_param
    username
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  inherit_resources
  respond_to :html, :xml, :json

  autocomplete :user, :username

  protected
    def resource
      @user ||= User.find_by_username! params[:id]
    end
end

app/views/users/_role.haml
%tr.user-role
  %td
    = user.username
  %td
    - if role.name == 'owner' or cannot?(:manage_users, role.resource)
      .pull-right.role-label= role.name.capitalize

    - else
      .btn-group.pull-right.btn-left-margin
        %a.btn.dropdown-toggle{:"data-toggle"=>"dropdown"}
          = role.name.capitalize
          %span.caret

        - # Drop down box to change the members permissions
        %ul.dropdown-menu
          - ['admin', 'member'].each do |role_option|
            %li
              - has_role = (role_option == role.name)
              - url = has_role ? "#" : add_role_user_print_queue_path(@user, @print_queue, :"role[user]" => user, :"role[name]" => role_option)
              = link_to url, ( has_role ? {} : {:remote => true} ) do
                - if has_role
                  .icon-check.icon-green
                - else
                  .icon-check-empty
                = role_option.capitalize

          %li.divider
          %li
            = link_to delete_role_user_print_queue_path(@user, @print_queue, :"role[user]" => user), {:remote => true} do
              .icon-remove.icon-red
              Revoke Access

app/views/users/_show.haml
.row.user-profile-page
  .span6
    = image_tag @user.gravatar_url(64), :class => "pull-left gravatar-large"
    %h2= @user

  .span6.print-queues-list
    .well
      %h3 #{@user == current_user ? "My" : "#{@user.username.capitalize}'s"} 3D Printers
      - if @user.print_queues.present?
        = render :partial => @user.print_queues
      - else
        .no-print-queues
          - if @user == current_user
            %p You don't seem to have any printer added yet.
            %p To add one, just fill in a name for your printer and we'll get started.
          - else
            %p #{@user} hasn't added any printers yet :(
      - if @user == current_user
        = form_for [@user, ( @print_queue || PrintQueue.new )], :html => {:class => "form form-horizontal form-add-print-queue"} do |f|
          = f.text_field :name, :placeholder => "Printer Name"
          = f.submit "Add Printer", :class => "btn btn-primary"

app/views/users/_user.haml
.container.user
  .row
    .span6
      = link_to user.username, user_path(user)

app/views/users/show.haml
= render :partial => "users/show"