config/routes.rb
CloudSlicer::Application.routes.draw do
  ActiveAdmin.routes(self)

  require 'resque/server'
  mount Resque::Server.new, :at => "/admin/resque"

  root :to => "home#index"

  devise_for :users, :path => '/', :path_names => {:registration => "register"}

  get 'autocomplete/user' => 'users#autocomplete_user_username'

  namespace :api do
    namespace :v1 do # TODO: :constraints => {:subdomain => "admin"}
      resource :print_queues, :path => "/:print_queue_id", :only => [:show, :update] do
        match "load_next_job"
        match "start_printing"
        match "finish_printing"
        get "print_jobs" => "print_jobs#index"
        resource :print_jobs, :path => "print_jobs/:id", :only => [:show, :update]
      end
    end
  end

  resources :users, :path => "/", :except => :index do

    resources :print_queues, :path => "/", :except => :index do
      match "add_role", :on => :member
      match "delete_role", :on => :member

      resources :print_jobs, :only => [:create, :update, :destroy, :index, :show_modal] do
        member do
          get "show_modal"
          get "download"
        end
      end

      resources :g_code_profiles do
        member do
          get "download"
        end
      end

    end

  end

end

app/models/g_code_profile.rb
require File.join Rails.root, "app", "uploaders", "slic3r_profile_uploader.rb"
require File.join Rails.root, "app", "models", "slic3r.rb"

class GCodeProfile < ActiveRecord::Base

  belongs_to :print_queue
  belongs_to :config_file

  has_many :print_jobs

  store :config
  attr_accessor :config_file_uploader
  mount_uploader :config_file_uploader, Slic3rProfileUploader

  def config_file_uploader_will_change!
    config_file_uploader.load_configs
  end
  def config_file_uploader_changed?
    false
  end

  def self.slic3r
    Slic3r.current_version
  end

  def slic3r
    Slic3r.current_version
  end

  # Defining Prefixed config store methods
  slic3r.safe_fields(true).each do |row|
    define_method(:"#{row}=") do |value|
      self.config_will_change!
      self.config.merge! row.to_s.sub(/(.*)_config_row/, '\1').to_sym => value
    end
    define_method(row) do
      self.config[row.to_s.sub(/(.*)_config_row/, '\1').to_sym]
    end
  end

  attr_accessible :name, :glob, :remote_config_file_url, :config_file_uploader, *(slic3r.safe_fields true)

  validates_uniqueness_of :name, :scope => :print_queue_id, :message => "^A profile with this name already exists"
  validates_uniqueness_of :glob, :scope => :print_queue_id, :message => "^A profile with the same url already exists"
  validates :name, :presence => true, :length => { :in => 1..35 }

  # Validating the configuration
  validate do
    if config_changed?
      update_config_file if config_file_dirty?
      # We run a test slic3r run to determine if their are any validation issues with the config file
      f = config_file.file.to_file
      test = slic3r.slice "/home/sliceruser/cube.stl", f.path, true

      slic3r.parseErrors(test[:std_io][:stderr]).each { |k,v| errors[k] = v }
    end
  end

  before_validation :on => :create do
    # Default to slic3r defaults for the config file
    self.config = slic3r.load if self.config.blank?
  end

  before_save do
    self.glob = name.urlize
  end

  def config= c
    write_attribute :config, c
    @config_file_dirty_flag = true
  end

  def config_file
    update_config_file if config_file_dirty?
    ConfigFile.find(read_attribute :config_file_id)
  end

  def config_file_dirty?
    !defined?(@config_file_dirty_flag) or @config_file_dirty_flag
  end

  def update_config_file
    @config_file_dirty_flag = false
    f = Tempfile.new(['slic3r_config_tmp_file','.ini'])
    begin
      f.write slic3r.serialize(config)
      @config_temp_file = f
      f.close(false)
      #raise IO.read f # for debugging
      self.config_file = ConfigFile.find_or_create_by_file f
      print_jobs.each &:file_changed
    ensure
      f.unlink
    end
  end

  def glob
    name.urlize
  end

  def to_s
    name
  end

end

app/controllers/g_code_profiles_controller.rb
class GCodeProfilesController < ApplicationController
  inherit_resources
  authorize_inherited_resource

  belongs_to :user, :finder => :find_by_username!
  belongs_to :print_queue, :finder => :find_by_glob!
  respond_to :json

  def create
    authorize! :manage_profiles, print_queue
    create! :notice => "Profile created successfully" do |success, failure|
      failure.html do
        flash[:error] = resource.errors.full_messages.join("<br/>").html_safe
        redirect_to user_print_queue_path(@print_queue.owner, @print_queue)
      end
      success.html do
        redirect_to user_print_queue_path(@print_queue.owner, @print_queue)
      end
    end

  end

  def update
    authorize! :manage_profiles, print_queue
    if resource.update_attributes(params["g_code_profile_#{resource.id}"]) then
      render :nothing => true
    else
      render :status => 500, :json => { :errors => resource.errors }
    end
  end

  def destroy
    authorize! :manage_profiles, print_queue
    resource.destroy
    redirect_to user_print_queue_path(@print_queue.owner, @print_queue)
  end

  def download
    redirect_to resource.config_file.file.url.gsub(/\?.*/, "")
  end

  private

    def print_queue
      @print_queue ||= PrintQueue.find_by_path!(params[:user_id], params[:print_queue_id])
    end

    def resource
      @g_code_profile ||= print_queue.g_code_profiles.where(:id => params[:id]).first
    end

end

app/views/g_code_profiles/_config_row.haml
- if can_edit
  - form_opts = case(type = meta[:type])
    - when 'double', 'int'
      - as = {"int" => :integer, "double" => :decimal}[type]
      - {:input_html => {"data-validation-type" => type}, :as => as }#, :step => ( type == "int" ? 1 : 0.1 ) }}
    - when 'select'
      - value_method = Proc.new {|o| o[1].present? ? o[1] : o[0]}
      - { :collection => meta[:options], :value_method => value_method, :label_method => Proc.new {|o| o[0]} }
    - when 'bool'
      - { :as => :boolean }
    - when 'text'
      - { :as => :text }
    - when 'coordinate'
      - html_opts = {:type => "number", :step => 1, "data-validation-type" => :integer}
      - { :as => :coordinates, :field_names_method =>  Proc.new {|i| :"#{name}_#{i}_config_row"}, :input_html => html_opts}
    - else
      - {}

  - hint = "<span class='units'>#{meta[:units]}</span>".html_safe
  - form_opts = {:label => meta[:title], :error => true, :hint => hint, :wrapper => :inline_hint, :input_html => {} }.merge form_opts

  = f.input :"#{name}_config_row", form_opts

- else
  .control-group
    - html = case(type = meta[:type])
      - when 'text'
        - raw(value).gsub("\n", "<br/>").html_safe
      - when 'coordinate'
        - [0,1].map{|i| g_code_profile.send :"#{name}_#{i}_config_row"}.join(" x ")
      - when 'bool'
        - f.input :"#{name}_config_row", :as => :boolean, :label => false, :disabled => true
      - when 'select'
        - (meta[:options].select{|o| o[1] == value}.first || meta[:options][0])[0]
      - when 'double', 'int'
        - value
      - else
        - value
    %label.control-label= meta[:title]
    .controls
      .input-append
        .input-placeholder= html
    

app/views/g_code_profiles/_g_code_profile.haml
.tab-pane{:id => "profile-#{g_code_profile.id}", :"data-profile-id" => g_code_profile.id, :class => (g_code_profile == @active_profile ? "active" : "")}

  - show_config = true
  - can_edit = can?(:edit, g_code_profile)

  - # Basic / Advanced Toggles
  - if show_config
    .config-mode.pull-right
      .btn-group{:"data-toggle"=>"buttons-radio"}
        %a.btn.active{:href => "#profile-#{g_code_profile.glob}-basic", :"data-toggle" => "tab"} Basic
        %a.btn{:href => "#profile-#{g_code_profile.glob}-advanced", :"data-toggle" => "tab"} Advanced

  - # Profile Name
  %h2.editable-attr.profile-name-js
    .pull-left= g_code_profile.name
    - if can_edit
      .btn.btn-primary.pull-left.btn-edit Edit
    .clear
  .editable-attr-edit.h2
    = form_for [g_code_profile.print_queue.owner, g_code_profile.print_queue, g_code_profile], :remote => true, :validate => true, :format => :json, :html => {:class => "form form-inline"} do |f|
      = f.text_field :name, :label => false, :class =>"pull-left"
      = f.submit "Save", :class => "btn btn-primary pull-left"
    .clear

  - if false # URL
    .editable-attr.g-code-profile-url
      = link_to g_code_profile.url
      - if can_edit
        .btn.btn-primary.btn-edit Edit
      .clear
    .editable-attr-edit.g-code-profile-url-edit
      = simple_form_for [g_code_profile.print_queue.owner, g_code_profile.print_queue, g_code_profile], :remote => true, :validate => true, :format => :json, :html => {:class => "form form-inline"} do |f|
        = f.submit "Save", :class => "btn btn-primary pull-right"
        = f.input :url, :label => false
      .clear

  - if show_config
    .tab-content.advanced-basic-tabs


      - # Basic Slic3r Configs
      - #--------------------------------------------------------------------------------------
      .tab-pane.basic-slic3r-settings-tab.active{:id => "profile-#{g_code_profile.glob}-basic"}
        = simple_form_for [@user, @print_queue, g_code_profile], :format => "json", :remote => true, :validate => true, :as => :"g_code_profile_basic_#{g_code_profile.id}" do |f|
          .form.form-horizontal
            %h3 Basic Settings
            .well
              - GCodeProfile.slic3r.commonly_used_fields.each do |attr_name, attr_meta_data|
                - value = g_code_profile.config[attr_name]
                - locals = { :name => attr_name, :meta => attr_meta_data, :value => value, :f => f, :can_edit => can_edit, :g_code_profile => g_code_profile }
                = render :partial => "/g_code_profiles/config_row", :locals => locals

          = link_to download_user_print_queue_g_code_profile_path( @user, @print_queue, g_code_profile ), :class => "pull-left btn" do
            %i.icon-download
            Download
          - if can_edit
            .g-code-profile-action-btns
              .btn-basic-profile-save.btn.btn-primary.pull-right Save Profile Changes
              %input.btn.pull-right{:type => "reset", :value => "Reset"}
              .saving-status.hide
                %i.icon-ok
                Saved

      - # Advanced Slic3r Configs
      - #--------------------------------------------------------------------------------------
      .tab-pane{:id => "profile-#{g_code_profile.glob}-advanced"}
        = simple_form_for [@user, @print_queue, g_code_profile], :format => "json", :remote => true, :validate => true, :as => :"g_code_profile_#{g_code_profile.id}" do |f|
          - first = true
          %ul.nav.nav-tabs
            - GCodeProfile.slic3r.ui_layout.each do |category, category_contents|
              %li{:class => (first == true ? "active" : "")}
                %a{:href=>"##{category.downcase.gsub(/[ _\/]/, "-")}-#{g_code_profile.glob}", :"data-toggle"=>"tab"}= category
              - first = false

          - first = true
          .tab-content.form.form-horizontal.advanced-slic3r-settings-tabs
            - GCodeProfile.slic3r.safe_ui_layout.each do |category, category_contents|
              .tab-pane{:id => "#{category.downcase.gsub(/[ _\/]/, "-")}-#{g_code_profile.glob}", :class => (first == true ? "active" : "")}
                - category_contents.each do |mid_category, mid_category_contents|
                  %h3= mid_category
                  - mid_category_contents.each do |sub_category, sub_category_contents|
                    .span8
                      %h4= sub_category
                      .well
                        - #raise sub_category_contents.class.to_s if sub_category_contents.class.to_s != "Hash"
                        - sub_category_contents.each do |attr_name, attr_meta_data|
                          - value = g_code_profile.config[attr_name]
                          - locals = { :name => attr_name, :meta => attr_meta_data, :value => value, :f => f, :can_edit => can_edit, :g_code_profile => g_code_profile }
                          = render :partial => "/g_code_profiles/config_row", :locals => locals
                  - first = false

          = link_to [@user, @print_queue, g_code_profile], :class => "pull-left btn" do
            %i.icon-download
            Download
          - if can_edit
            .g-code-profile-action-btns
              = f.submit "Save Profile Changes", :class => "btn btn-primary pull-right btn-advanced-profile-save"
              %input.btn.pull-right{:type => "reset", :value => "Reset"}
              .saving-status.hide
                %i.icon-ok
                Saved